name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Firebase Login with Personal Token
        run: echo "${{ secrets.FIREBASE_TOKEN }}" | firebase login:ci --no-localhost

      - name: Install project dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project ohbakai
