name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # デプロイするブランチを指定

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase Hosting
        run: firebase deploy --project ${{ secrets.PROJECT_ID }} --only hosting
      - name: Get Firebase Hosting URL
        id: firebase-url
        run: echo "::set-output name=url::$(firebase hosting:site https://${{ secrets.PROJECT_ID }}.web.app)"
      - name: Output URL
        run: echo "Deployed to ${{ steps.firebase-url.outputs.url }}"
