name: Firebase Deploy

on:
  push:
    branches:
      - main  # デプロイするブランチを指定 (必要に応じて変更)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 使用するNode.jsのバージョンを指定 (必要に応じて変更)

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Login to Firebase
        uses: wzieba/firebase-login@v1
        with:
          token: ${{ secrets.FIREBASE_TOKEN }} # 後で説明

      - name: Install project dependencies
        run: npm install # 必要に応じてpackage.jsonを使用する

      - name: Build the application
        run: npm run build # または、あなたのプロジェクトのビルドコマンド

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project ohbakai

      - name: Run tests (optional)
        run: npm test # テストを実行したい場合に追加

